trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: '<your-service-connection-name>'
  resourceGroupName: 'myResourceGroup'
  location: 'eastus'

steps:
- task: AzureCLI@2
  displayName: 'Deploy Windows VM'
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment group create \
        --name $(Build.BuildId)-vm \
        --resource-group $(resourceGroupName) \
        --template-file ./windows-vm.bicep \
        --parameters adminUsername='yourAdminUsername' adminPassword='yourAdminPassword' \
        --location $(location)

- task: AzurePowerShell@5
  displayName: 'Verify VM Deployment'
  inputs:
    azureSubscription: $(azureServiceConnection)
    ScriptPath: './verify-vm-deployment.ps1'
    ScriptArguments: '-ResourceGroupName $(resourceGroupName)'

- task: AzureCLI@2
  displayName: 'Deploy Azure SQL Database'
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment group create \
        --name $(Build.BuildId)-sql \
        --resource-group $(resourceGroupName) \
        --template-file ./azure-sql.bicep \
        --parameters sqlDatabaseName='mySQLDB' sqlAdministratorLogin='sqladmin' sqlAdministratorLoginPassword='YourStrongPassword123!' \
        --location $(location)

- task: AzurePowerShell@5
  displayName: 'Verify SQL Deployment'
  inputs:
    azureSubscription: $(azureServiceConnection)
    ScriptPath: './verify-sql-deployment.ps1'
    ScriptArguments: '-ResourceGroupName $(resourceGroupName)'